PPOController:
  # Velocity limits
  max_linear_vel: 0.8
  max_angular_vel: 1.0
  min_linear_vel: -0.5
  min_angular_vel: -1.0
  
  # Goal tolerance
  goal_tolerance: 0.2
  
  # Safety parameters
  obstacle_threshold: 0.5
  
  # Laser scan parameters
  laser_scan_size: 360
  
  # PPO agent parameters
  training_mode: false
  model_save_path: "$(find ppo_controller)/models/ppo_navigation_model.zip"
  tensorboard_log_dir: "$(find ppo_controller)/logs/tensorboard/"
  ppo_script_path: "$(find ppo_controller)/scripts/ppo_agent.py"
  
  # Reward function weights
  reward_goal_weight: 10.0
  reward_collision_weight: -10.0
  reward_smooth_weight: -0.1
  reward_progress_weight: 1.0
  
  # Control parameters  
  max_v: 0.8
  min_v: -0.5
  max_v_inc: 0.5
  max_w: 1.0
  min_w: -1.0
  max_w_inc: 1.0
  
  # Controller base parameters
  goal_dist_tol: 0.2
  rotate_tol: 0.5
  lookahead_time: 1.0
  min_lookahead_dist: 0.5
  max_lookahead_dist: 3.0