shutdown_costmaps: false

planner_frequency: 0.25 #0 当收到新的导航目标时。当前的路径被障碍物阻塞时。才会重规划调用make_plan服务
planner_patience: 5.0

controller_frequency: 20.0
controller_patience: 15.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

conservative_reset_dist: 3.0

# TF transform tolerance
transform_tolerance: 2.0
